Fixed time.sleep() function in async call & 2025 HA compatibility
rospogrigio/airbnk_mqtt pull request #50
Opened 2024-12-07 11:20 UTC by adlertag1

Issue Description
The original issue occurred in the airbnk_mqtt custom Home Assistant integration when handling MQTT messages for a Tasmota-based lock device. The log contained the following error:

RuntimeError: Caught blocking call to sleep with args (0.5,) inside the event loop by custom integration 'airbnk_mqtt' at custom_components/airbnk_mqtt/tasmota_device.py, line XXX

The problem was caused by the use of the time.sleep() function in an asynchronous context (async def). Blocking calls like time.sleep() are not allowed in asynchronous environments in Home Assistant as they can freeze the event loop.

Solution
The solution was to replace the blocking time.sleep() function with the asynchronous await asyncio.sleep() function.

Example of the Fix:
Before:

if self.curr_try < self.retries_num:
self.curr_try += 1
time.sleep(0.5) # Blocking call that caused the error
self.logger.debug("Retrying: attempt %i" % self.curr_try)
After:

if self.curr_try < self.retries_num:
self.curr_try += 1
await asyncio.sleep(0.5) # Non-blocking, asynchronous sleep
self.logger.debug("Retrying: attempt %i" % self.curr_try)
This modification ensures that the integration adheres to the non-blocking, asynchronous principles of Home Assistant's core framework.

Additional Context
The issue was specifically related to the retry logic in the async_parse_MQTT_message method, which attempts to resend frames after a failed connection (state: FAILCONNECT). The fix allows the integration to handle such failures gracefully without impacting the Home Assistant event loop.

2025 HA compatibility:

Replaced Deprecated Constants:

Replaced DEVICE_CLASS_SIGNAL_STRENGTH, ELECTRIC_POTENTIAL_VOLT, and TIME_SECONDS with: SensorDeviceClass.SIGNAL_STRENGTH
UnitOfElectricPotential.VOLT
UnitOfTime.SECONDS
Updated Cover Entity Constants:

Replaced SUPPORT_CLOSE and SUPPORT_OPEN with:
CoverEntityFeature.CLOSE
CoverEntityFeature.OPEN
Fixed async_forward_entry_setup Usage:

Added await before all async_forward_entry_setup calls to ensure proper asynchronous execution and to comply with Home Assistant 2025.1 requirements. Ensured Compatibility with Future Home Assistant Versions:

Addressed all deprecation warnings and updated the code to align with Home Assistant's latest API standards.

2025-01-04 23:28 UTC, rospogrigio requested changes

2025-01-04 23:28 UTC, rospogrigio commented on custom_components/airbnk_mqtt/cover.py
> +    async def async_open_cover(self, **kwargs):
Remove space at the end

2025-01-04 23:28 UTC, rospogrigio commented on custom_components/airbnk_mqtt/cover.py
> +    async def async_close_cover(self, **kwargs):
Remove space at the end

2025-01-04 23:28 UTC, rospogrigio commented on custom_components/airbnk_mqtt/gra.txt
What is this file? I think it should be removed

2025-01-04 23:28 UTC, rospogrigio commented on custom_components/airbnk_mqtt/sensor.py
> +        return self._sensor.get("device_class")
Are you sure there is no constant for this string in SensorDeviceClass ?

2025-01-05 08:57 UTC, adlertag1 commented on custom_components/airbnk_mqtt/sensor.py
> +        return self._sensor.get("device_class")
You’re absolutely right; there is a constant for this in SensorDeviceClass. I've updated the code to use SensorDeviceClass.DEVICE_CLASS instead of the hardcoded "device_class" string.

2025-01-05 08:57 UTC, adlertag1 commented on custom_components/airbnk_mqtt/gra.txt
Yes, this was a mistake. :)

2025-01-05 14:07 UTC, rospogrigio approved these changes

2025-01-05 14:07 UTC, merged